### ISSUE TITLE
Single line of lore does not displayed

### ISSUE THREAD

**Issue by Malpl3naInk** [ToberoCat/GuiEngine#1]
I was following the User Beginner Guide and I found when I add single lore to a item, it does not displayed
![image](https://github.com/ToberoCat/GuiEngine/assets/80235192/968a6d0b-8929-48fb-a2bc-03ad5ae2dd23)
![image](https://github.com/ToberoCat/GuiEngine/assets/80235192/34da83bf-6e7b-4c6a-aba0-fa789183f5a2)

I found that `ParserContext.getOptionalStringArray()` used foreach to process the lore array, but when there have only one lore, the `getOptionalNode()` returned JsonNode is String instead of Array
![image](https://github.com/ToberoCat/GuiEngine/assets/80235192/fa6c75f5-225a-4a82-9051-a81e1d731934)
![image](https://github.com/ToberoCat/GuiEngine/assets/80235192/2081fb90-b8f3-4e1c-aa1a-fe4afea351dd)

**Comment by ToberoCat** [comment]
Thanks for reporting this issue. I'll take a look at fixing it right now.

**Comment by Malpl3naInk** [comment]
This is my solution:
![image](https://github.com/ToberoCat/GuiEngine/assets/80235192/d872005f-90d3-485c-9ca4-79b8f0f0a9f6)
It works correctly

**Comment by ToberoCat** [comment]
Thanks I've used your implementation with some minor changes. Bug will now be fixed in the newer version of the plugin

**Comment by ToberoCat** [comment]
If you happen to come across a bug and manage to resolve it locally, please feel free to submit a pull request.
