### ISSUE TITLE
Lost on-click function after edit

### ISSUE THREAD

**Issue by Malpl3naInk** [ToberoCat/GuiEngine#2]
In this component:
```
<component type="item" id="green-button" x="3" y="2" material="GREEN_TERRACOTTA" name="§aGreen button">
    <lore>§7Click me</lore>
    <lore>§7I promise §ait's worth§7 it</lore>
    <on-click type="edit" target="green-button" attribute="name" set-value="§eYou clicked me :)"/>
    <on-click type="edit" target="green-button" attribute="material" set-value="YELLOW_TERRACOTTA"/>
</component>
```
After clicked once, the GREEN_TERRACOTTA replaced by YELLOW_TERRACOTTA, and the name changed
And then, if I continue to click, it will cause error:
```
[22:06:10 ERROR]: Could not pass event InventoryClickEvent to GuiEngine v1.2.1
java.lang.NullPointerException: Cannot invoke "io.github.toberocat.guiengine.function.GuiFunction.call(io.github.toberocat.guiengine.GuiEngineApi, io.github.toberocat.guiengine.context.GuiContext)" because "function" is null
```
I found that in [DefaultInterpreter.java](https://github.com/ToberoCat/GuiEngine/blob/master/src/main/java/io/github/toberocat/guiengine/interpreter/DefaultInterpreter.java#L90) , after convertValue() method, the `on-click` will filled with null
![image](https://github.com/ToberoCat/GuiEngine/assets/80235192/cdc418e9-a015-4d99-b2a9-919f32492d35)
![image](https://github.com/ToberoCat/GuiEngine/assets/80235192/551fe999-d922-40a9-b5c4-43251cbf89f3)

**Comment by ToberoCat** [comment]
Are you able to capture the output of this method when calling it the first time (When the context is getting generated the first time)?
Maybe there's an issue withthe serialization of the component's functions

**Comment by Malpl3naInk** [comment]
yes, this is the first output, it logged when server start
![image](https://github.com/ToberoCat/GuiEngine/assets/80235192/990ed70b-da15-4151-b70f-7479c629b71f)
It handled two items
And then, this logged when I opened the GUI
![image](https://github.com/ToberoCat/GuiEngine/assets/80235192/803c2ead-08ef-4f53-aedd-ca9722e3a5f9)
Next, I clicked the item
![image](https://github.com/ToberoCat/GuiEngine/assets/80235192/b02495c8-b041-446f-bea5-5a2889a5c87c)

**Comment by ToberoCat** [comment]
Thank you. I already see the issue lies in the serializsation of the item component. When you look at the first image and the last one, you can see that the on-click suddenly became a array, losing the type property.

I'll see how I can fix it

**Comment by ToberoCat** [comment]
Alright. Fixed the problem. New version has already been rolled out
