### ISSUE TITLE
How to use the PagedComponent

### ISSUE THREAD

**Issue by Malpl3naInk** [ToberoCat/GuiEngine#3]
Is this code correct?
```xml
<gui title="§eTag" width="9" height="2">
    <component type="item" material="IRON_BLOCK" name="§eBack">
        <on-click type="action">[container:previous]</on-click>
    </component>
    <component type="item" x="8" material="DIAMOND_BLOCK" name="§eNext">
        <on-click type="action">[container:next]</on-click>
    </component>
    <component type="paged" id="container" y="1" width="9" height="1" interactions="true"
            pattern="0,1,2,3,4,5,6,7,8">
        <fill-empty type="item" material="GLASS_PANE">
            <on-click type="action">[message] Nothing here</on-click>
        </fill-empty>
        <page>
            <component type="item" x="1" material="EMERALD_BLOCK" name="§ePage 1">
                <on-click type="action">[message] Page 1</on-click>
            </component>
        </page>
        <page>
            <component type="item" x="7" material="REDSTONE_BLOCK" name="§ePage 2">
                <on-click type="action">[message] Page 2</on-click>
            </component>
        </page>
    </component>
</gui>
```

**Comment by ToberoCat** [comment]
Looks right, except the part where you define the pages manually in the component. All compontens get assigned a page, x and y automatically based on your pattern provided.

A version that would fix the component might look like this:

```xml
<component type="paged" id="container" y="1" width="9" height="1" interactions="true"
            pattern="0,1,2,3,4,5,6,7,8">
        <fill-empty type="item" material="GLASS_PANE">
            <on-click type="action">[message] Nothing here</on-click>
        </fill-empty>
            <component type="item" material="EMERALD_BLOCK" name="§eItem 1">
                <on-click type="action">[message] Page 1</on-click>
            </component>
            <component type="item" material="REDSTONE_BLOCK" name="§eItem 2">
                <on-click type="action">[message] Page 2</on-click>
            </component>
    </component>
```

Btw sorry for the bad code style, I'm on mobile and it's not that great to edit code on there.

Basically what the component does, it takes your all items you give it in the body and places them in the slots you defined in the pattern attribute. When the last slot in the pattern is reached, it will create a new page and start assigning the items to the pattern from the beginning again

**Comment by Malpl3naInk** [comment]
It displayed in game looks like this:
![image](https://github.com/ToberoCat/GuiEngine/assets/80235192/ee0d5087-48b2-4fb4-a29d-6c2c385fd261)
If I wanted to move two items below to right, how can I do this, add a "x" property to component or what

By the way, the code for this image is already added the "x" property

**Comment by ToberoCat** [comment]
All you have to do is adjust the pattern. Take a look at a chest UI with the slots. Then you can change the order of the slots / remove slots / add other slots

**Comment by Malpl3naInk** [comment]
Um... whitch pattern?

Btw when it has nine items, it will switch to next page when I clicked Next Button. Is it normal?

**Comment by ToberoCat** [comment]
The property pattern. In the example you sent above, it's set to 0,1,2,3,4,5,6,7,8

You mean the page is empty with just nine components? If that's the case, I'll have to see and fix that

**Comment by Malpl3naInk** [comment]
> The property pattern. In the example you sent above, it's set to 0,1,2,3,4,5,6,7,8

Ok, it works

> You mean the page is empty with just nine components? If that's the case, I'll have to see and fix that

This is the testing code:
```xml
<gui title="§eTag" width="9" height="2">
    <component type="item" material="IRON_BLOCK" name="§eBack">
        <on-click type="action">[container:previous]</on-click>
    </component>
    <component type="item" x="8" material="DIAMOND_BLOCK" name="§eNext">
        <on-click type="action">[container:next]</on-click>
    </component>
    <component type="paged" id="container" y="1" width="9" height="1" interactions="true"
            pattern="0,1,2,3,4,5,6,7,8">
        <component type="item" material="EMERALD_BLOCK" name="§eItem 1">
            <on-click type="action">[message] Item 1</on-click>
        </component>
        <component type="item" material="REDSTONE_BLOCK" name="§eItem 2">
            <on-click type="action">[message] Item 2</on-click>
        </component>
        <component type="item" material="REDSTONE_BLOCK" name="§eItem 3">
            <on-click type="action">[message] Item 3</on-click>
        </component>
        <component type="item" material="REDSTONE_BLOCK" name="§eItem 4">
            <on-click type="action">[message] Item 4</on-click>
        </component>
        <component type="item" material="REDSTONE_BLOCK" name="§eItem 5">
            <on-click type="action">[message] Item 5</on-click>
        </component>
        <component type="item" material="REDSTONE_BLOCK" name="§eItem 6">
            <on-click type="action">[message] Item 6</on-click>
        </component>
        <component type="item" material="REDSTONE_BLOCK" name="§eItem 7">
            <on-click type="action">[message] Item 7</on-click>
        </component>
        <component type="item" material="REDSTONE_BLOCK" name="§eItem 8">
            <on-click type="action">[message] Item 8</on-click>
        </component>
        <component type="item" material="REDSTONE_BLOCK" name="§eItem 9">
            <on-click type="action">[message] Item 9</on-click>
        </component>
    </component>
</gui>
```
When I opened the menu:
![image](https://github.com/ToberoCat/GuiEngine/assets/80235192/4f785c09-0f0a-4f0e-99e5-999b7212bc0a)
And then, I clicked the Next button(Diamond Block):
![image](https://github.com/ToberoCat/GuiEngine/assets/80235192/da6d4d3e-5967-4307-a538-e31e7fc028b0)
If I remove the Item 9, nothing will happen when I clicken Next button(It is correctly)

**Comment by Malpl3naInk** [comment]
It seems that when the last slot of line have item, then click the Next button will switch to an empty page

And when I click the item below, the page will become like this(no matter the on-click is exists):
![image](https://github.com/ToberoCat/GuiEngine/assets/80235192/8f534144-e33b-48b4-a08f-0124cf150420)
The line above will be replaced by copy of the line below
If the height of PagedComponent is 2:
![image](https://github.com/ToberoCat/GuiEngine/assets/80235192/9559b254-9fc4-49db-9046-6c9f3a6cfaee)
But the item is still work on its location. For example, if I clicked the Emerald Block, it still execute what Iron Block do

**Comment by ToberoCat** [comment]
Alright. Good the see that it kinda works. Once I'm home from work I'll take a look at it and see if I can fix it

**Comment by Malpl3naInk** [comment]
> Btw when it has nine items, it will switch to next page when I clicked Next Button. Is it normal?

I fixed this problem in [Pull Request](https://github.com/ToberoCat/GuiEngine/pull/4)

It caused because when adding the last item, the `currentPatternIndex < pattern.length` will be `false` then create a new empty page, but there is no more items so it left an empty page behind

**Comment by ToberoCat** [comment]
Alright, thanks. I'll take a look at it

**Comment by ToberoCat** [comment]
Okay, approved & merged the pull request. Thanks for fixing it again. You can close the issue if you no longer need something

**Comment by Malpl3naInk** [comment]
There is still have problem [here](https://github.com/ToberoCat/GuiEngine/issues/3#issuecomment-1671155358)
I'm working on it but have no progress

**Comment by ToberoCat** [comment]
Can you send me the gui file that produced this gui? I'll take a look at it

**Comment by Malpl3naInk** [comment]
The gui code is same as [this](https://github.com/ToberoCat/GuiEngine/issues/3#issuecomment-1671137940)

**Comment by Malpl3naInk** [comment]
> The line above will be replaced by copy of the line below

I fixed this in [Pull Request](https://github.com/ToberoCat/GuiEngine/pull/5) with details because maybe it will have better solution

**Comment by ToberoCat** [comment]
Oh, thank you. I'll take a look at it. I've got stuck in a rabbit hole of fixing the paged component's api, as the code for the paged component isn't really that great.

**Comment by ToberoCat** [comment]
Fixed it based on your observations with a cleaner implementation

**Comment by Malpl3naInk** [comment]
Besides, could I share this plugin to mcbbs.net, a Minecraft forum in China? I will forward the download link to Github

**Comment by ToberoCat** [comment]
Yeah, sure. As long as it stays free and open source you should be able to do it form the license side.

For me it wouldn't be an issue too
