### ISSUE TITLE
Add better invaild GUi error handling

### ISSUE THREAD

**Issue by Josh65-2201** [ToberoCat/GuiEngine#6]
## Description
Currently when making a GUI and it has an issue (currently tested with Improved Factions ones), I get a big not useful java error. What It should show is the file location including name and line number it has an issue with parsing

## Steps to reproduce 
None

## Logs
None

## Versions
Server: Paper 1.20.1 build 108
GUI engine: 1.2.3

**Comment by ToberoCat** [comment]
Would you be able to send me the error you've been able to reproduce, because there is a system in place that should provide more useable error messages, so that is probably something more critical.

**Comment by Josh65-2201** [comment]
[error.txt](https://github.com/ToberoCat/GuiEngine/files/12337533/error.txt)

**Comment by ToberoCat** [comment]
Look at the console when reloading the server or using /guiengine reload.

Looks like the issue is that improved factions doesn't handle errors from guiengine correct yet

**Comment by Josh65-2201** [comment]
Doing `/guiengine reload` gives the same error and one maybe causing Improved Faction to not load
[error.txt](https://github.com/ToberoCat/GuiEngine/files/12339384/error.txt)

**Comment by ToberoCat** [comment]
Thanks, I'll see if I can improve this, as it can't stay like that

**Comment by Josh65-2201** [comment]
Found the issue to be this file [rank-overview.txt](https://github.com/ToberoCat/GuiEngine/files/12389399/rank-overview.txt). Don't know what I did wrong when editing it but deleting it and restart fixes the issues.

**Comment by jokbon** [comment]
these mistakes are taken from "home depot" shops which specifies how long object is. 
They usualy mix up coodinates in theyr naming. Because how long is becomes height, since its most important to a costumer it gets specified first, but coordinates are specified:
X 
Y 
Z,
While home depots specify them incorectly as:
Y
X 
Z.

**Comment by jokbon** [comment]
![image](https://github.com/ToberoCat/GuiEngine/assets/29400409/2e1b5858-c201-4649-ab9e-ca431fc5b1b1)
